name: fga-cyclic-design
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - biopython
  - openpyxl
  - pyyaml
  - pytest
  - matplotlib
  - tqdm
  - pip
